version: '3.0'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    hostname: zoo1
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todo
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_admin

